import { StyleSheet } from "react-native"

const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 15,
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    headertext: {
        flex: 1,
        paddingHorizontal: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    iconimage: {
        width: 50,
        height: 50,
        marginVertical: 10,
        marginHorizontal: 10,
        borderRadius: 25,
        overflow: 'hidden', 
        justifyContent: 'center',
        alignItems: 'center',
    },
    textheader: {
        fontSize: 23,
        marginLeft: 10,
        marginRight: 10,
        marginLeft: 10,
        color: '#ffffff',
        fontWeight: 'bold',
        textShadowColor: '#000',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 3,
    },
    viewlist: {
        flex: 1,
        marginBottom: 20,
        paddingHorizontal: 10,
    },
    listQ: {
        flexGrow: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    QA: {
        flexDirection: 'row',
        width: '90%',
        height: 60,
        backgroundColor: 'rgba(255, 255, 255, 0.8)', 
        marginBottom: 15,
        borderRadius: 15,
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
    },
    textid: {
        width: '40%',
        justifyContent: 'center',
        alignItems: 'center',
        fontSize: 18,
        marginLeft: 20,
        fontWeight: '500',
        color: '#003459',
    },
    textPoints: {
        width: '20%',
        fontSize: 18,
        fontWeight: 'bold',
        color: '#d1001f',
    },
    iconquestion: {
        marginRight: 20,
        width: 30,
        height: 30,
        borderRadius: 15,
    },
    nextbutton: {
        width: 50,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#ffffff',
        borderRadius: 25,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
    },
});

export default styles;